### ISSUE TITLE
SWY rain events data need is not bold

### ISSUE THREAD

**Issue by dcdenu4** [natcap/invest.users-guide#9]
SWY rain events data need is not bolded like the other inputs.

**Comment by richpsharp** [comment]
Hey Doug, it's fine with me if you want to directly change things and push them on to the UG. It doesn't undergo the same rigor as our software does and I'd rather get fixes in there instead of being drown in issues with typos or what not. Anyway, feel free to fix anything as you see it. James has the pipeline set up so it'll rebuild and publish if there's no problems and otherwise kick an error and not break anything if there is a problem.

**Comment by dcdenu4** [comment]
Will do! I just saw this as an aside and didn't want to get distracted from what I was working on. But I guess the amount of time spent making this issue has already eclipsed the time it would have taken to bold that text... and now that I'm typing this I could have re-wrote a whole user guide section! haha

**Comment by dcdenu4** [comment]
Fixed
